# Generated by Django 5.2.10 on 2026-01-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('vendedor', models.CharField(blank=True, max_length=120)),
                ('numero_nf', models.CharField(blank=True, max_length=60)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('arquivo_pdf', models.FileField(upload_to='notas_fiscais/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='licencas.fornecedor')),
            ],
            options={
                'ordering': ['-data_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_serial', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('LIVRE', 'Livre'), ('EM_USO', 'Em uso')], default='LIVRE', max_length=10)),
                ('usuario_atual', models.CharField(blank=True, help_text="Obrigatório apenas quando o status for 'Em uso'.", max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('compra_nf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencas', to='licencas.compranf')),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LicencaUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=120)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_uso', to='licencas.licenca')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(choices=[('MICROSOFT', 'Microsoft'), ('COREL', 'Corel'), ('ADOBE', 'Adobe'), ('OUTRO', 'Outro')], default='MICROSOFT', max_length=20)),
                ('linha', models.CharField(help_text='Ex: Windows, Windows Server, Office, CorelDRAW', max_length=80)),
                ('versao_edicao', models.CharField(help_text='Ex: 11 Pro, Server 2022 Standard, Office 2021, etc.', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['fabricante', 'linha', 'versao_edicao'],
                'unique_together': {('fabricante', 'linha', 'versao_edicao')},
            },
        ),
        migrations.AddField(
            model_name='licenca',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencas', to='licencas.produto'),
        ),
    ]
