# Generated by Django 5.2.10 on 2026-01-17 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='licenca',
            options={},
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='licenca',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='licenca',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licencas', to='licencas.departamento'),
        ),
    ]
